my_string =input("Привет, как тебя зовут? ")
print(len(my_string))
print(my_string.upper())
print("Привет,",my_string,"!")
print("my_string".upper())
print("my_string".lower())
print("my_string".replace("_",""))
print("my_string"[1])
print("my_string"[-1])

